# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Amal Dev Haridevan
"""Generate catalogs and API inputs from the adjacent gz-drl source."""

from __future__ import annotations

import ast
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib


@dataclass(frozen=True)
class Page:
    title: str
    summary: str
    docname: str
    order: int
    metadata: dict[str, Any]


def _front_matter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise RuntimeError(f"Catalog page is missing YAML front matter: {path}")
    parts = text.split("---\n", 2)
    if len(parts) != 3:
        raise RuntimeError(f"Unterminated YAML front matter: {path}")
    data = yaml.safe_load(parts[1]) or {}
    if not isinstance(data, dict):
        raise RuntimeError(f"Front matter must be a mapping: {path}")

    return data


def _catalog_pages(srcdir: Path, section: str) -> list[Page]:
    pages: list[Page] = []
    for index in (srcdir / section).glob("*/index.md"):
        metadata = _front_matter(index)
        if metadata.get("catalog", True) is False:
            continue
        title = str(metadata.get("title", "")).strip()
        summary = str(metadata.get("summary", "")).strip()
        if not title or not summary:
            raise RuntimeError(f"Catalog page needs title and summary: {index}")
        pages.append(
            Page(
                title=title,
                summary=summary,
                docname=index.relative_to(srcdir).with_suffix("").as_posix(),
                order=int(metadata.get("order", 999)),
                metadata=metadata,
            )
        )
    return sorted(pages, key=lambda page: (page.order, page.title.casefold()))


def _validate_source_version(source_dir: Path, expected: str) -> None:
    cmake = (source_dir / "CMakeLists.txt").read_text(encoding="utf-8")
    match = re.search(
        r"project\s*\(\s*gzdrl\b.*?\bVERSION\s+([0-9]+\.[0-9]+\.[0-9]+)",
        cmake,
        re.IGNORECASE | re.DOTALL,
    )
    if match is None or match.group(1) != expected:
        found = match.group(1) if match else "missing"
        raise RuntimeError(f"gz-drl CMake version is {found}; pyproject.toml declares {expected}")

    python_version = source_dir / "GzDRL" / "_version.py"
    if python_version.is_file():
        match = re.search(
            r"^__version__\s*=\s*[\"']([^\"']+)[\"']",
            python_version.read_text(encoding="utf-8"),
            re.MULTILINE,
        )
        if match is None or match.group(1) != expected:
            found = match.group(1) if match else "missing"
            raise RuntimeError(
                f"gz-drl Python version is {found}; pyproject.toml declares {expected}"
            )

    package_metadata = source_dir / "pyproject.toml"
    if package_metadata.is_file():
        metadata = tomllib.loads(package_metadata.read_text(encoding="utf-8"))
        found = str(metadata.get("project", {}).get("version", "missing"))
        if found != expected:
            raise RuntimeError(
                f"gz-drl package version is {found}; pyproject.toml declares {expected}"
            )


def _validate_environment_ids(srcdir: Path, source_dir: Path) -> None:
    binding = source_dir / "envs" / "gazebo_envpool" / "gazebo_envpool_envs.cc"
    text = binding.read_text(encoding="utf-8")
    expected = {
        f"GazeboPool{env_class}-v0"
        for env_class in re.findall(
            r"MAKE_PY_GAZEBO_ENVPOOL\(\s*m\s*,\s*([A-Za-z_]\w*)\s*,", text
        )
    }
    documented = {
        str(_front_matter(path).get("env_id", ""))
        for path in (srcdir / "environments").glob("*/index.md")
        if _front_matter(path).get("catalog", True)
    }
    if expected != documented:
        missing = sorted(expected - documented)
        stale = sorted(documented - expected)
        raise RuntimeError(
            "Environment documentation does not match native bindings; "
            f"missing={missing}, stale={stale}"
        )


def _card_details(section: str, page: Page) -> str:
    if section == "environments":
        return (
            f"`{page.metadata['env_id']}`  \n"
            f"Observation: `{page.metadata['observation']}` · "
            f"Action: `{page.metadata['action']}`"
        )
    tags = page.metadata.get("tags", [])
    return " · ".join(f"`{tag}`" for tag in tags)


def _write_catalog(srcdir: Path, section: str) -> None:
    pages = _catalog_pages(srcdir, section)
    output = srcdir / "_generated" / f"{section}-catalog.md"
    lines = [
        "<!-- Generated by docs/_ext/gzdrl_docs.py. Do not edit. -->",
        "",
        "::::{grid} 1 2 2 2",
        ":gutter: 2",
        "",
    ]
    for page in pages:
        lines.extend(
            [
                f":::{'{'}grid-item-card{'}'} {page.title}",
                f":link: /{page.docname}",
                ":link-type: doc",
                "",
                page.summary,
                "",
                _card_details(section, page),
                ":::",
                "",
            ]
        )
    lines.extend(["::::", "", "```{toctree}", ":hidden:", ":maxdepth: 1", ""])
    lines.extend(f"../{page.docname}" for page in pages)
    lines.extend(["```", ""])
    output.write_text("\n".join(lines), encoding="utf-8")


def _line_number(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def _mask_cpp_comments(text: str) -> str:
    """Hide C++ comments while preserving every character and line offset."""

    masked = list(text)

    def hide(start: int, end: int) -> None:
        for position in range(start, end):
            if masked[position] not in "\r\n":
                masked[position] = " "

    index = 0
    while index < len(text):
        if text.startswith("//", index):
            end = text.find("\n", index + 2)
            end = len(text) if end < 0 else end
            hide(index, end)
            index = end
            continue
        if text.startswith("/*", index):
            close = text.find("*/", index + 2)
            end = len(text) if close < 0 else close + 2
            hide(index, end)
            index = end
            continue

        # Preserve raw pybind11 docstrings, including comment-like prose.
        if text.startswith('R"', index):
            delimiter_end = text.find("(", index + 2, index + 20)
            if delimiter_end >= 0:
                delimiter = text[index + 2 : delimiter_end]
                if len(delimiter) <= 16 and not re.search(r"[\s()\\]", delimiter):
                    terminator = ")" + delimiter + '"'
                    raw_end = text.find(terminator, delimiter_end + 1)
                    if raw_end >= 0:
                        index = raw_end + len(terminator)
                        continue

        if text[index] in {'"', "'"}:
            quote = text[index]
            index += 1
            while index < len(text):
                if text[index] == "\\":
                    index += 2
                    continue
                if text[index] == quote:
                    index += 1
                    break
                index += 1
            continue
        index += 1

    return "".join(masked)


_BINDING_MEMBER = re.compile(
    r"(?<![A-Za-z0-9_])\."
    r"(?P<kind>def|def_(?:readwrite|readonly)(?:_static)?|"
    r"def_property(?:_readonly)?(?:_static)?)"
    r"\(\s*(?:(?P<quoted>\"(?P<name>[^\"]+)\")|(?P<init>py::init))"
)


def _binding_summary(segment: str) -> str:
    """Return the first prose line from a pybind11 raw docstring."""

    raw_docs = re.findall(r'R"pbdoc\((.*?)\)pbdoc"', segment, re.DOTALL)
    if not raw_docs:
        return ""
    for line in raw_docs[-1].splitlines():
        summary = line.strip()
        if summary:
            summary = re.sub(r"\s+", " ", summary)
            return summary[:197] + "..." if len(summary) > 200 else summary
    return ""


def _binding_arguments(segment: str) -> list[str]:
    arguments: list[str] = []
    for name in re.findall(r'py::arg(?:_v)?\(\s*"([^\"]+)"', segment):
        if name not in arguments:
            arguments.append(name)
    return arguments


def _binding_entries(body: str, base_offset: int) -> list[tuple[int, str, str]]:
    """Extract source-backed Python argument names from one class binding chain."""

    hits = list(_BINDING_MEMBER.finditer(body))
    entries: list[tuple[int, str, str]] = []
    for index, match in enumerate(hits):
        end = hits[index + 1].start() if index + 1 < len(hits) else len(body)
        segment = body[match.start() : end]
        kind = match.group("kind")
        name = "__init__" if match.group("init") else match.group("name")
        arguments = _binding_arguments(segment)
        if kind.startswith("def_property") or kind.startswith("def_read"):
            signature = name
        elif arguments:
            signature = f"{name}({', '.join(arguments)})"
        elif name == "__init__" and re.search(r"py::init\s*<\s*>", segment):
            signature = "__init__()"
        else:
            signature = f"{name}(…)"
        entries.append(
            (base_offset + match.start(), signature, _binding_summary(segment))
        )
    return entries


def _python_signature(node: ast.FunctionDef, *, drop_self: bool = False) -> str:
    arguments = ast.unparse(node.args)
    if drop_self:
        if arguments == "self":
            arguments = ""
        elif arguments.startswith("self, "):
            arguments = arguments[len("self, ") :]
    returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return f"{node.name}({arguments}){returns}"


def _registry_inventory(path: Path, source_url: str, source_ref: str) -> str:
    text = path.read_text(encoding="utf-8")
    tree = ast.parse(text)
    registry_class = next(
        (
            node
            for node in tree.body
            if isinstance(node, ast.ClassDef) and node.name == "EnvRegistry"
        ),
        None,
    )
    if registry_class is None:
        raise RuntimeError("envs/registration.py does not define EnvRegistry")

    methods = {
        node.name: node
        for node in registry_class.body
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_")
    }
    aliases: dict[str, int] = {}
    for node in tree.body:
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and isinstance(node.value, ast.Attribute)
            and isinstance(node.value.value, ast.Name)
            and node.value.value.id == "registry"
        ):
            aliases[node.targets[0].id] = node.lineno

    public_order = (
        "make",
        "make_spec",
        "make_gym",
        "make_gymnasium",
        "make_dm",
        "list_all_envs",
        "register",
    )
    missing = [name for name in public_order if name not in methods or name not in aliases]
    if missing:
        raise RuntimeError(f"envs registry inventory is missing public aliases: {missing}")

    relative = path.relative_to(path.parents[1]).as_posix()
    file_url = f"{source_url}/blob/{source_ref}/{relative}"
    lines = [
        "## `gzdrl.envs` registry",
        "",
        "`gzdrl.envs` re-exports these callables from the global `EnvRegistry` "
        "instance:",
        "",
    ]
    for name in public_order:
        node = methods[name]
        signature = _python_signature(node, drop_self=True)
        doc = ast.get_docstring(node) or "Public environment-registry callable."
        method_link = f"{file_url}#L{node.lineno}"
        alias_link = f"{file_url}#L{aliases[name]}"
        lines.append(
            f"- [`gzdrl.envs.{signature}`]({method_link}) — {doc} "
            f"([public alias]({alias_link}))"
        )
    return "\n".join(lines)


def _binding_inventory(source_dir: Path, source_url: str, source_ref: str) -> str:
    sections: list[str] = []
    binding_files = sorted((source_dir / "GzDRL" / "python").glob("*.cc"))
    binding_files += sorted((source_dir / "sitl" / "python").glob("*.cc"))

    for path in binding_files:
        text = path.read_text(encoding="utf-8", errors="replace")
        search_text = _mask_cpp_comments(text)
        class_hits: list[tuple[int, str]] = []
        for match in re.finditer(r"(?m)^[ \t]*py::class_<", search_text):
            nearby = search_text[match.start() : match.start() + 700]
            name_match = re.search(r"\(\s*m\s*,\s*\"([^\"]+)\"", nearby)
            if name_match:
                class_hits.append((match.start(), name_match.group(1)))
        global_hits = list(
            re.finditer(r"(?m)^[ \t]*m\.def\(\s*\"([^\"]+)\"", search_text)
        )
        if not class_hits and not global_hits:
            continue

        relative = path.relative_to(source_dir).as_posix()
        file_url = f"{source_url}/blob/{source_ref}/{relative}"
        lines = [f"## `{relative}`", ""]
        for index, (offset, name) in enumerate(class_hits):
            boundaries = [len(search_text)]
            if index + 1 < len(class_hits):
                boundaries.append(class_hits[index + 1][0])
            boundaries.extend(
                match.start() for match in global_hits if match.start() > offset
            )
            end = min(boundaries)
            body = search_text[offset:end]
            members = _binding_entries(body, offset)
            line = _line_number(text, offset)
            link = f"[{name}]({file_url}#L{line})"
            declaration_end = members[0][0] - offset if members else min(len(body), 1000)
            summary = _binding_summary(body[:declaration_end])
            heading = f"### {link}"
            lines.extend([heading, ""])
            if summary:
                lines.extend([summary, ""])
            if members:
                for member_offset, signature, member_summary in members:
                    member_line = _line_number(text, member_offset)
                    item = f"- [`{signature}`]({file_url}#L{member_line})"
                    if member_summary:
                        item += f" — {member_summary}"
                    lines.append(item)
            else:
                lines.append("- Constructor or attributes only.")
            lines.append("")

        if global_hits:
            lines.extend(["### Module functions", ""])
            event_offsets = sorted(
                [offset for offset, _ in class_hits]
                + [match.start() for match in global_hits]
                + [len(search_text)]
            )
            for match in global_hits:
                end = next(offset for offset in event_offsets if offset > match.start())
                segment = search_text[match.start() : end]
                arguments = _binding_arguments(segment)
                name = match.group(1)
                signature = f"{name}({', '.join(arguments)})" if arguments else f"{name}(…)"
                line = _line_number(text, match.start())
                item = f"- [`{signature}`]({file_url}#L{line})"
                summary = _binding_summary(segment)
                if summary:
                    item += f" — {summary}"
                lines.append(item)
            lines.append("")
        sections.append("\n".join(lines))

    registration = source_dir / "envs" / "registration.py"
    sections.append(_registry_inventory(registration, source_url, source_ref))

    helper_files = [source_dir / "GzDRL" / "_paths.py"]
    helper_lines = ["## Python path helpers", ""]
    for path in helper_files:
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        tree = ast.parse(text)
        relative = path.relative_to(source_dir).as_posix()
        file_url = f"{source_url}/blob/{source_ref}/{relative}"
        names = [
            node
            for node in tree.body
            if isinstance(node, ast.FunctionDef) and not node.name.startswith("_")
        ]
        if names:
            helper_lines.extend([f"### `{relative}`", ""])
            for node in names:
                signature = _python_signature(node)
                doc = ast.get_docstring(node)
                item = f"- [`{signature}`]({file_url}#L{node.lineno})"
                if doc:
                    item += f" — {doc.splitlines()[0]}"
                helper_lines.append(item)
    sections.append("\n".join(helper_lines))

    return "\n\n".join(
        [
            "# Python API",
            "",
            "This inventory is generated at documentation-build time from the configured "
            "pybind11 binding sources and public Python helpers. It does not import Gazebo "
            "or start a simulation.",
            "",
            f"Source revision: [`{source_ref[:12]}`]({source_url}/tree/{source_ref})",
            "",
            *sections,
            "",
            "```{note}",
            "For native bindings, this source inventory reports Python argument names where "
            "the binding declares `py::arg`. The pybind11 docstrings in an installed wheel "
            "remain the authority for overload types and defaults. Use "
            "`help(gzdrl.DRLServer)` or `help(gzdrl.sitl.RosDRLServer)` against the wheel installed "
            "in your target environment.",
            "```",
            "",
        ]
    )


def _run_doxygen(source_dir: Path, output_dir: Path, version: str) -> Path:
    executable = shutil.which("doxygen")
    if executable is None:
        raise RuntimeError("Doxygen is required to build the C++ API reference")
    output_dir.mkdir(parents=True, exist_ok=True)
    inputs = [
        source_dir / "GzDRL" / "include",
        source_dir / "envs",
        source_dir / "sitl" / "include",
    ]
    config = "\n".join(
        [
            "PROJECT_NAME = GzDRL",
            f"PROJECT_NUMBER = {version}",
            f'OUTPUT_DIRECTORY = "{output_dir}"',
            "GENERATE_HTML = NO",
            "GENERATE_LATEX = NO",
            "GENERATE_XML = YES",
            "XML_OUTPUT = xml",
            "QUIET = YES",
            "WARNINGS = NO",
            "EXTRACT_ALL = YES",
            "EXTRACT_PRIVATE = NO",
            "EXTRACT_STATIC = YES",
            "RECURSIVE = YES",
            "FILE_PATTERNS = *.h *.hh *.hpp",
            "FULL_PATH_NAMES = YES",
            "STRIP_FROM_PATH = " + str(source_dir),
            "ENABLE_PREPROCESSING = YES",
            "MACRO_EXPANSION = NO",
            "HAVE_DOT = NO",
            "INPUT = " + " ".join(f'\"{path}\"' for path in inputs if path.is_dir()),
            "EXCLUDE_PATTERNS = */envs/envpool/* */experiments_paper/* "
            "*/tests/* */inv_pendul_test.hh */_lib/* */build/*",
        ]
    )
    result = subprocess.run(
        [executable, "-"],
        input=config,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    if result.returncode != 0:
        raise RuntimeError("Doxygen failed:\n" + result.stdout)
    xml_dir = output_dir / "xml"
    if not (xml_dir / "index.xml").is_file():
        raise RuntimeError("Doxygen did not produce index.xml")
    return xml_dir


def prepare(srcdir: Path, repository_root: Path) -> dict[str, str]:
    """Build the catalogs and API reference from this repository checkout."""
    source_dir = repository_root.resolve()
    metadata = tomllib.loads((source_dir / "pyproject.toml").read_text(encoding="utf-8"))
    version = metadata["project"]["version"]
    source_url = "https://github.com/amaldevh/gz-drl"
    revision = subprocess.run(
        ["git", "-C", str(source_dir), "rev-parse", "HEAD"],
        check=True, capture_output=True, text=True,
    ).stdout.strip()
    (srcdir / "_generated").mkdir(exist_ok=True)
    _validate_source_version(source_dir, version)
    _validate_environment_ids(srcdir, source_dir)

    for section in ("modules", "environments", "examples"):
        _write_catalog(srcdir, section)

    generated_api = _binding_inventory(source_dir, source_url, revision)
    (srcdir / "_generated" / "python-api.md").write_text(generated_api, encoding="utf-8")
    xml_dir = _run_doxygen(source_dir, srcdir / "_build" / "doxygen", version)
    return {
        "source_dir": str(source_dir),
        "source_url": source_url,
        "source_ref": revision,
        "version": version,
        "doxygen_xml": str(xml_dir),
    }
